services:
  frontend:
    container_name: moutarde-frontend-dev
    build:
     context: ./moutarde-front
     dockerfile: Dockerfile.dev
    ports:
     - "5180:5180"
    volumes:
      - ./moutarde-front:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped

  backend:
    build:
      context: ./moutarde-back
      dockerfile: Dockerfile.dev
    container_name: moutarde-backend-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5181
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=moutarde_db_dev;Username=postgres;Password=postgres
    ports:
      - "5181:5181"
    volumes:
      - ./moutarde-back:/app
      - /app/moutarde-back/bin
      - /app/moutarde-back/obj
    depends_on:
      database:
          condition: service_healthy
    restart: unless-stopped
  
  database:
    image: postgres:alpine
    container_name: moutarde-database-dev
    environment:
      - POSTGRES_DB=moutarde_db_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
volumes:
  postgres_dev_data: