FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY *.sln ./
COPY moutarde-back/*.csproj ./moutarde-back/
RUN dotnet restore

COPY . .
WORKDIR /src/moutarde-back
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 80

CMD ["dotnet", "moutarde-back.dll"]